language: java
addons:
  sonarcloud:
    organization: "mihanloko"
    token:
      secure: "GPAO5ZWW6QvjQITogdzu1DpLxuJgLKmLuQCDlHlfUyN1Wxm9AC1/J8buEjylLMmy6dmScQx6x5/fiW9jbdTJcGvAj1Xy5ncE5ou+qRVU+ef3SxGiscPDDVvw+sILAYNsI6X26zv5xfyug4ldPWGevkIcwTN4ztqB2Q8D4W8/OA6YjKjY9nA2YJlrYC0mnz2hRme14VJ6pgNg4VLT6HkrkCapAteMCYenTxuU7JSM/rhsoa/Y4i8PNo2VW3aJW92StXQ/jGxWcboP7V5+Au2IGMZ89UQEI4e64vH9zbcdj7muJrcH4J1/HE53EWIGko4I15bBoVZgwy3omwKBE3TKHtyZm2mfMwkDXNRWBw0XkZGQAI9Wb4SY4k8+sY1THtwhZR7repYwjhZL3bMjZVPcAWY7lSqVxU0+pqQFBZaFkZ/yN0IdSj+DNUvySt4Ci9rxhANdqtBCTFSxXQVz4onMgbufWR7NneqlsbTiFHDlZufxFf8xUl2e/+TnIh2dC/NFqMud8RqP7kD39jssRVRzenDUmqKjTEWVvD7YFOuR/NqS3GvYPK8pcXxXuxaf4FoZWVfXJhYWUVNMDMbqyHvVc+YO15OxhvGLrxDfJStiKqlE3Y/0OF0cIgHN+eueliwiIOx1CgKxawSdzlX5/Ipb/CyIy+Dzg86jcisB2SpPZhM="
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=mihanloko_testing_things