language: java
addons:
  sonarcloud:
    organization: "mihanloko"
    token:
      secure: "IAx2UFsYxhomw+NTHkOeE8VPhs+T947p2wkTn0wCXt0v6QW+4rzXuB6wMKoF8eUH/7//hF7xJHTDfq7F/UAotdFBzwxkcLWpIwNfjHVydjyhcRFTLnivYAFOrYQmh8iYnuyy+H7U30w21dM/A4kydeZp5mnK1F5a8Fpi3ZZdSHN1/RU1E8jJA4Z4W2wlqAnAuomjFs3i9RRjUooRa7K96uxg4Nhca/IXY3G+aLtgeVr5vRgg7EgNvZE8asYe4FrUg9cBa2BcQkeZOO1gCAK0Mqdwf5pc7/fx0X52T2PQWAlViNPc/VatbQRZkyG2jyh3TMtZ4pdy9XhHVhuI1bcRnO3o48DrnRICvaEeuFI328yzoPhPkgAfN46x7izixlk/au7+9+tFhXjm4IFwFzZ4cDppaParFHVRTCKaUb6ZuL26xUI7Rs+kFQTZ7VnhedYBtGWG4fX5KRfe0wqqduC6x81Q9wb3xPo+ebgRzxQbQMa58TG4ufbvf6texqQTV7qeui0uJ2HfIiXVwBqP+XPMRTGTA4UCkrZ0YgHb322kXbI0NvshD8qKTR87VKAS5n06DATW8t8rZlv1IiNZmM4AP1ekzrl08EzVbSTJICD0kbPv9880dW1jLqm05x+yfMHCqPSKFy0iiUTH/GvAwDFo+hVdC6HVOBNXDicuonNUPrw="
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=mihanloko_testing_things