language: java
addons:
  sonarcloud:
    organization: "mihanloko"
    token:
      secure: "dcF2vLTPkR6GJlCsjKm9rxsxKuZ3w6wswkmdWN+ZfXZT0P6FMXZo97C5FnNR5MTpJ3d15TWS3cugv9KtRdOAGS9cA7SAAXxPNx5bIdidJYQl/FGHj+/oFt93AQQgFpVRX5jgru36ccnxln715EuI2x3fi6EvObbIIb5u9kFZLDURqWL75/b4ZdE9rBiBFJhEUBXDR5/EC5YBezAC/aI9uOgT7gk8LPt7hWavanisG0JwO9M8aZV/6/rIrPpytwuixBal6tjaD7UF/ZrmoBKcLd45JiM6hqTCz77QZA5kcndH8KuqCXStqvZXQzeig4TRnvWqzw5rjLFqnVgZcUTADueMUkqNl7wKahGU6E5CEhEqE9liOjNlayd+T3EQSSBSfPcy7csAZl2USsYHlczSXfsaPvlNeJu5OID6muGmc7HT7+9a0k6kdnCkCypPkse1u0bJuuK3JqLILdsjubHwJZP16mxQRNCfukixl96dRswRyxcEJ2PsxTTZCfH/EkJdLjH4Ua7tQD5OyWLjrP63x3hqDfBx2C0x/ISsa9tGtrLyEirA8f4yCwvxPbJpnmlUZzUloZhrzvEC6amoRcdPuco23vYhjeWHg1jL1KapK4nz2r2YiKi5LXbauOUxuO0aCoFvts2CxPe6gNIcKd1kaNiioFN5x0Zqc3bvWN3rWrY="
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=mihanloko_testing_things